export const FILLHD = 'FILLHD'
export const FILLSD = 'FILLSD'
export const ORDERALFA = 'ORDERALFA'
export const ORDEROPOSITEALFA = 'ORDEROPOSITEALFA'
export const ORDERALFASEARCH = 'ORDERALFASEARCH'
export const ORDEROPOSITEALFASEARCH = 'ORDEROPOSITEALFASEARCH'

